### ISSUE TITLE
extend kubernetes-client to openshift-client

### ISSUE THREAD

**Issue by debianmaster** [godaddy/kubernetes-client#105]
i would like to extend this k8s library to openshift which has additional objects like `Route`  `DeploymentConfig`  etc  can you please  guide me the steps that would be involved ?

**Comment by silasbw** [comment]
@debianmaster created a PR that has a rough outline for adding support to this code base for new "API groups": https://github.com/godaddy/kubernetes-client/pull/106/files#diff-6a3371457528722a734f3c51d9238c13R33

I notice https://github.com/debianmaster/openshift-client -- cool!  I think we should be able to expose the right interface from `kubernetes-client` so that `openshift-client` can depend on `kubernetes-client` (instead of forking it).  Would you be interested in trying that approach?

**Comment by debianmaster** [comment]
@silasbw  definitely ! i dont want to re-invent wheel.   `I think we should be able to expose the right interface from kubernetes-client so that openshift-client can depend on kubernetes-client`  i think this is the ideal way.   lets chat more on the PR you created.

**Comment by silasbw** [comment]
@debianmaster check out https://github.com/silasbw/openshift-client-scratch.  Does that seem like a good approach?

Tests are the main thing missing -- we can pull https://github.com/godaddy/kubernetes-client/blob/master/test/common.js out into a module (e.g., `kubernetes-client-test`) so other packages can re-use it.

**Comment by debianmaster** [comment]
@silasbw sorry the late reply.  in travel right now.  but i will check and get back in a day.

**Comment by silasbw** [comment]
Seems like we have a path forward with https://github.com/debianmaster/openshift-client, so I'm going to close this issue.  Feel free to re-open if we need more discussion.
