### ISSUE TITLE
Working with helm

### ISSUE THREAD

**Issue by subhankarc** [godaddy/kubernetes-client#348]
Hi,

Is there a way we can work with helm charts with this library?

**Comment by silasbw** [comment]
Can you be more specific?  What are you hoping to do?

**Comment by vivekzhere** [comment]
@silasbw We are trying to generate actual yamls from a helm chart.

**Comment by silasbw** [comment]
So, you want to use kubernetes-client to script helm operations, instead of using the helm client?

**Comment by vivekzhere** [comment]
We could not find any native helm client for nodejs.

**Comment by ajpauwels** [comment]
@vivekzhere There is no native helm client in just about any language, all that exists is the Helm CLI. Communication with the Tiller server is non-trivial and requires use of GRPC instead of HTTP, which means you'll need to use protobufs and a GRPC comms library instead of the traditional request/axios/etc libs. This also means it would not be able to simply re-use the requests system built by `kubernetes-client`. Building a native helm client in nodejs would be (in my opinion, keep in mind I am NOT a member of the godaddy team building `kubernetes-client`, just an enthusiastic user) a project unto itself, worthy of being a separate node module.

However, in terms of a practical solution, I recommend you rely on using the Helm CLI binary for now and using the `spawn` API in nodejs to spawn instances of the CLI to perform your actions. This is what I've been doing and it works well, although it has several caveats:
- Can't pass in-mem objects around, so you'll need to write out your kubeconfig/values.yaml files to the disk before invoking `spawn`
- It is, obviously, dependent on the environment the app is running in having the Helm CLI binary installed
- Helm CLI hangs execution when it has to wait on certain hooks to complete and those hooks do not complete, this means your entire app could potentially hang due to a bad Helm call. I've gotten around this by using `setTimeout` and calling `.kill()` on the object returned by `spawn` when my timeout is exceeded.

**Comment by vivekzhere** [comment]
@ajpauwels Thank you for the inputs.
