### ISSUE TITLE
Generates a client for IBMCloud users

### ISSUE THREAD

**Issue by sophiac0120** [godaddy/kubernetes-client#349]
Hi, has anyone successfully generated a IBM Cloud client via IAM token or user/password authentification? There is a similar example for a AWK user, I believe it's called something i-am authorization and it seems very similar to the configuration of IBM Cloud Kubernetes cluster. Has anyone have any idea?

**Comment by ajpauwels** [comment]
Your infrastructure's host shouldn't matter, all that matters is the kubeconfig. I've successfully used this module to communicate with IBM Kubernetes Service clusters. Just download the kubeconfig file using the ibmcloud CLI, and then I use this code to load it up and get a client:

```
const Kubernetes = require('kubernetes-client');
const K8sClient = Kubernetes.Client;
const K8sConfig = Kubernetes.config;

const configObj = K8sConfig.fromKubeconfig(kubeconfigCopy);
const client = new K8sClient({config: configObj});
```

**Comment by silasbw** [comment]
Thanks for following up @ajpauwels :hand: .

Is there a feature/fix request for kubernetes-client?  Even something like better docs / examples?

**Comment by ajpauwels** [comment]
@silasbw I think one potential point of improvement in the docs is to clarify what the different options are for providing a kubeconfig. I think that it's initially unclear that the lib loads from the `KUBECONFIG` env by default, especially to someone who may be brand new to Kubernetes (I admit it: this was me...oops). It's also unclear that you can provide an object to the `fromKubeconfig` call in order to not load from env, which is helpful to for people passing around kubeconfigs in-mem.

**Comment by silasbw** [comment]
Closing this because @ajpauwels nicely helped clarify usage in the README.md
