### ISSUE TITLE
Promises based API

### ISSUE THREAD

**Issue by kjvalencik** [godaddy/kubernetes-client#37]
It would be nice if this library also supported promises. Unfortunately, wrapping the `request` library for promises is fairly [non-trivial](https://github.com/request/promise-core/blob/master/lib/plumbing.js). This makes it a bit unwieldy to promisify at runtime.

The [request-promise](https://github.com/request/request-promise) library also supports a `nodeify` method for callbacks, allowing simulataneous support for callbacks and promises. However, this may make streaming more cumbersome.

Perhaps a provide your own `request` library approach?

**Comment by silasbw** [comment]
Sorry for the delay @kjvalencik -- this is something we'd consider implementing, but it hasn't been high on our priority list because we usually eschew promises.

I think the first step would be rejiggering kubernetes-client a little bit to facilitate adding promise support.  If you have some concrete thoughts here, we'd love to hear them.

Second step would then be actually adding the promise support.  Either as an option to kubernetes-client, or as a separate `kubernetes-client-promises` wrapper package.

**Comment by kjvalencik** [comment]
There are a few things that I think could be helpful to allow integrating promises externally:

* Ensure all calls return their result. This is also useful if you want to stream the response.
* Optional config to pass the `request` library in.
* There are a few places in the code that don't check that a parameter exists before grabbing a value off it. These work because a `callback` is usually passed. Without it you will get an `undefined` deref error.
* Pass `json: true` to `request` so that parsing happens in the library instead of in a callback.

Open questions:

* How to implement retry logic that works regardless of `request` library?
* What to do with methods that do work in a wrapping callback before handing off to a user callback?
* How to test to prevent regressions in promise functionality?

**Comment by silasbw** [comment]
@kjvalencik helpful list -- if we could rejigger things so that switching to promise mode was as easy as passing in the `request` library, that would be great.  I'd worry about making the `kubernetes-client` code opaque and cumbersome to maintain, but that's a qualitative thing that would be hard to evaluate without looking at a PR first.

re: `json: true` -- there's reason we didn't do that to begin with and it's that when set and `content-type: application/strategic-merge-patch+json`, `request` (essentially) ignores `json: true` so our client code ends up implementing the JSON decoding anyways.  To be consistent we just don't set it.  We've meant to address this issue via a PR to `request`, but haven't done it yet.

**Comment by silasbw** [comment]
We should consider adding a promise-based API to kubernetes-client:

```js
const api = require('kubernetes-client/async');
const core = new api.Core(api.config.fromKubeconfig());

async function main() {
  const pods = await core.ns.po.get();
  console.log(`Watching: ${ JSON.stringify(pods, null, 2) }`);
  const stream = core.ns.po.getStream({ qs: { watch: true }});
  stream.on('data', data => { console.log(data.toString()); });
  stream.on('error', err => { throw err; });
  stream.on('end', () => { console.log('end'); });
}
main();
```

Any feedback on the following:
1. including a promised-based API (_v.s._, an external wrapper `kubernetes-client-promise`);
1. `[method]Stream` functions (_e.g._, `getStream`);
1. API location and name (kubernetes-client/async);

or something else?

**Comment by TWood67** [comment]
@silasbw 
1. I think it would be best to include the promised base API in this module. I can see the advantages of having an external wrapper, but I've seen plenty of them neglected because they aren't a priority. Separation would also make regression tests for promises more difficult to manage, IMO. 
2. I can think of one additional option here... We could return a Promise for calls to `.stream`. I like the solution here
https://github.com/petkaantonov/bluebird/issues/332#issuecomment-58326173
However this doesn't handle `stream.on('data', dataHandler)` so we would need to write something for that.  
3. I would lean towards something like `kubernetes-client/promise`. `async` doesn't imply a promise library.

**Comment by silasbw** [comment]
Added **experimental** support with 3.16.0.
