### ISSUE TITLE
multi resource json 

### ISSUE THREAD

**Issue by ledger1go** [godaddy/kubernetes-client#433]
hello,
help me, please
I want to create multiple resources with a single json file.

**Comment by silasbw** [comment]
Hi, this probably falls outside the scope of kubernetes-client since we don't provide any support for loading resource files (i.e., we expect users to use the json/yaml/whatever parser they want).

kubectl supports multiple resources per-yaml file (https://stackoverflow.com/questions/52255883/kubernetes-application-with-multiple-resources-single-yaml).  I'm not sure if there's a parser for this in Node/js or not.  If you find one or implement one, please let us know.
