### ISSUE TITLE
job and job status read operations

### ISSUE THREAD

**Issue by naseemkullah** [godaddy/kubernetes-client#451]
Hi,

It seems that both

[apis.batch.v1.namespaces(namespace).jobs(name).status.get
](https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/Job.md#apisbatchv1namespacesnamespacejobsnamestatusget) and
[apis.batch.v1.namespaces(namespace).jobs(name).get
](https://github.com/godaddy/kubernetes-client/blob/master/docs/1.13/Job.md#apisbatchv1namespacesnamespacejobsnameget)

return the same result, namely the full job object.

I was expecting the former to be a only a subset of this though, namely the status portion of the object.

Could you confirm what I am seeing and address the problem or suggest a workaround?

Thanks,
Naseem

**Comment by silasbw** [comment]
It looks like that's the expected behavior.  E.g.,

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#read-job-v1-batch

vs

https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#read-status-job-v1-batch

(both responses are [Job](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#job-v1-batch))

**Comment by naseemkullah** [comment]
Ah I see, thanks!
