### ISSUE TITLE
k8.ns.pvc.matchLabels gives 404

### ISSUE THREAD

**Issue by nick** [godaddy/kubernetes-client#90]
I used to be able to call the following:

    k8.ns.pvc.matchLabels({ app: 'test' }).get((err, sRes) => {

but that now gives a 'resource not found' error. I now have to call the following instead:

    k8.ns.pvc.get({ qs: { labelSelector: 'app=test' } }, (err, sRes) => {

**Comment by silasbw** [comment]
Ugh, sorry about that.  #91 is a fix.  We do have a test for this (https://github.com/godaddy/kubernetes-client/blob/master/test/api-group.test.js#L208), but it "just happens to still work" because of how we've implemented `Pods` (https://github.com/godaddy/kubernetes-client/blob/master/lib/pods.js#L42).

**Comment by silasbw** [comment]
@nick we published `kubernetes-client@3.10.1` with the fix.  Thanks for the bug report.
